apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-app
  template:
    metadata:
      labels:
        app: devops-app
    spec:
      containers:
        - name: flask-app
          image: arnn019/devops-app:1ffeb96a706afe6d772cf06516e2d6925f977f34
          ports:
            - containerPort: 80
